### ISSUE TITLE
Unable to get attachmentID in payload.body

### ISSUE THREAD

**Issue by johansja** [craigp/elixir-gmail#8]
When getting a message, attachmentID is missing in payload.body.
https://developers.google.com/gmail/api/v1/reference/users/messages/get
https://developers.google.com/gmail/api/v1/reference/users/messages/attachments#resource

**Comment by johansja** [comment]
Fixed in https://github.com/craigp/elixir-gmail/pull/9

**Comment by craigp** [comment]
PR merged in, thanks 👍
